//
// Auto-generated asset manifest - DO NOT EDIT MANUALLY
// Generated by NoZ Game Engine Asset Importer
//

// @includes
#include <noz/noz.h>
#include <memory.h>

// @constants
#define ASSET_TOTAL_MEMORY 45708

// @globals
static arena_allocator_t* g_asset_allocator = NULL;

// @assets
struct
{
    struct
    {
        Shader* border_effect;
        Shader* _default;
        Shader* gamma;
        Shader* gizmo;
        Shader* lit;
        Shader* shadow;
        Shader* text;
        Shader* ui;
        Shader* vignette;
    } shaders;
} g_assets;

// @init
bool assets_init(void)
{
    if (g_asset_allocator != NULL)
        return false; // Already initialized

    g_asset_allocator = arena_allocator_create(ASSET_TOTAL_MEMORY);
    if (!g_asset_allocator)
        return false;

    NOZ_ASSET_LOAD(Shader, "shaders/border_effect", g_assets.shaders.border_effect);
    NOZ_ASSET_LOAD(Shader, "shaders/default", g_assets.shaders._default);
    NOZ_ASSET_LOAD(Shader, "shaders/gamma", g_assets.shaders.gamma);
    NOZ_ASSET_LOAD(Shader, "shaders/gizmo", g_assets.shaders.gizmo);
    NOZ_ASSET_LOAD(Shader, "shaders/lit", g_assets.shaders.lit);
    NOZ_ASSET_LOAD(Shader, "shaders/shadow", g_assets.shaders.shadow);
    NOZ_ASSET_LOAD(Shader, "shaders/text", g_assets.shaders.text);
    NOZ_ASSET_LOAD(Shader, "shaders/ui", g_assets.shaders.ui);
    NOZ_ASSET_LOAD(Shader, "shaders/vignette", g_assets.shaders.vignette);

    return true;
}

// @uninit
void assets_uninit(void)
{
    if (g_asset_allocator != NULL)
    {
        arena_allocator_destroy(g_asset_allocator);
        g_asset_allocator = NULL;
        
        // Clear all asset pointers
        memset(&g_assets, 0, sizeof(g_assets));
    }
}
