//
// Auto-generated asset manifest - DO NOT EDIT MANUALLY
// Generated by NoZ Game Engine Asset Importer
//

// @includes
#include <noz/noz.h>
#include "assets.h"

// @constants
#define ASSET_TOTAL_MEMORY 5312332

// @globals
static arena_allocator_t* g_asset_allocator = nullptr;

// @assets
Assets Assets = {};

// @init
bool LoadAssets()
{
    if (g_asset_allocator != nullptr)
        return false; // Already initialized

    g_asset_allocator = arena_allocator_create(ASSET_TOTAL_MEMORY);
    if (!g_asset_allocator)
        return false;

    NOZ_ASSET_LOAD(Font, "fonts/Roboto-Black", Assets.fonts.roboto_black);
    NOZ_ASSET_LOAD(Shader, "shaders/border_effect", Assets.shaders.border_effect);
    NOZ_ASSET_LOAD(Shader, "shaders/default", Assets.shaders._default);
    NOZ_ASSET_LOAD(Shader, "shaders/gamma", Assets.shaders.gamma);
    NOZ_ASSET_LOAD(Shader, "shaders/gizmo", Assets.shaders.gizmo);
    NOZ_ASSET_LOAD(Shader, "shaders/lit", Assets.shaders.lit);
    NOZ_ASSET_LOAD(Shader, "shaders/shadow", Assets.shaders.shadow);
    NOZ_ASSET_LOAD(Shader, "shaders/text", Assets.shaders.text);
    NOZ_ASSET_LOAD(Shader, "shaders/ui", Assets.shaders.ui);
    NOZ_ASSET_LOAD(Shader, "shaders/vignette", Assets.shaders.vignette);
    NOZ_ASSET_LOAD(Texture, "textures/grid", Assets.textures.grid);
    NOZ_ASSET_LOAD(Texture, "textures/icons/meshes/buildings/extractor", Assets.textures.icons.meshes.buildings.extractor);
    NOZ_ASSET_LOAD(Texture, "textures/icons/meshes/buildings/Stone", Assets.textures.icons.meshes.buildings.stone);
    NOZ_ASSET_LOAD(Texture, "textures/palette", Assets.textures.palette);

    return true;
}

// @uninit
void UnloadAssets()
{
    if (g_asset_allocator != nullptr)
    {
        arena_allocator_destroy(g_asset_allocator);
        g_asset_allocator = nullptr;
        
        // Clear all asset pointers
        memset(&Assets, 0, sizeof(Assets));
    }
}
