//
// Auto-generated asset header - DO NOT EDIT MANUALLY
// Generated by NoZ Game Engine Asset Importer
//

// @fonts
// Assets.fonts.roboto_black
//
// @shaders
// Assets.shaders.border_effect
// Assets.shaders._default
// Assets.shaders.gamma
// Assets.shaders.gizmo
// Assets.shaders.lit
// Assets.shaders.shadow
// Assets.shaders.text
// Assets.shaders.ui
// Assets.shaders.vignette
//
// @textures
// Assets.textures.grid
// Assets.textures.icons.meshes.buildings.extractor
// Assets.textures.icons.meshes.buildings.stone
// Assets.textures.palette
//

#pragma once

// Forward declarations
struct Shader;
struct Texture;
struct Mesh;
struct Font;
struct Material;
struct Sound;

struct Assets
{
    struct
    {
        Font* roboto_black;
    } fonts;
    struct
    {
        Shader* border_effect;
        Shader* _default;
        Shader* gamma;
        Shader* gizmo;
        Shader* lit;
        Shader* shadow;
        Shader* text;
        Shader* ui;
        Shader* vignette;
    } shaders;
    struct
    {
        struct
        {
            struct
            {
                struct
                {
                    Texture* extractor;
                    Texture* stone;
                } buildings;
            } meshes;
        } icons;
        Texture* grid;
        Texture* palette;
    } textures;
};

extern Assets Assets;

bool LoadAssets();
void UnloadAssets();
