//
// Auto-generated asset header - DO NOT EDIT MANUALLY
// Generated by NoZ Game Engine Asset Importer
//

// @fonts
// LoadedAssets.fonts.roboto_black
//
// @shaders
// LoadedAssets.shaders.border_effect
// LoadedAssets.shaders._default
// LoadedAssets.shaders.gamma
// LoadedAssets.shaders.gizmo
// LoadedAssets.shaders.lit
// LoadedAssets.shaders.shadow
// LoadedAssets.shaders.text
// LoadedAssets.shaders.ui
// LoadedAssets.shaders.vignette
//
// @textures
// LoadedAssets.textures.grid
// LoadedAssets.textures.icons.meshes.buildings.extractor
// LoadedAssets.textures.icons.meshes.buildings.stone
// LoadedAssets.textures.palette
//

#pragma once

// Forward declarations
struct Shader;
struct Texture;
struct Mesh;
struct Font;
struct Material;
struct Sound;

struct LoadedAssets
{
    struct
    {
        Font* roboto_black;
    } fonts;
    struct
    {
        Shader* border_effect;
        Shader* _default;
        Shader* gamma;
        Shader* gizmo;
        Shader* lit;
        Shader* shadow;
        Shader* text;
        Shader* ui;
        Shader* vignette;
    } shaders;
    struct
    {
        struct
        {
            struct
            {
                struct
                {
                    Texture* extractor;
                    Texture* stone;
                } buildings;
            } meshes;
        } icons;
        Texture* grid;
        Texture* palette;
    } textures;
};

extern LoadedAssets Assets;

bool LoadAssets(size_t arena_size = 0);
void UnloadAssets();
