//
// Auto-generated asset manifest - DO NOT EDIT MANUALLY
// Generated by NoZ Game Engine Asset Importer
//

#include <noz/noz.h>

#define ASSET_TOTAL_MEMORY 10

// Global asset structure
struct {
    int a;
} g_assets;

// Load all assets into single arena
bool noz_assets_load_all(void) {
    arena_allocator_t* arena = arena_allocator_create(ASSET_TOTAL_MEMORY);
    if (!arena) return false;


    return true;
}
