//
// Auto-generated asset manifest - DO NOT EDIT MANUALLY
// Generated by NoZ Game Engine Asset Importer
//

// @includes
#include <noz/noz.h>
#include "assets.h"

// @globals
static Allocator* g_asset_allocator = nullptr;

// @assets
LoadedAssets Assets = {};

// @init
bool LoadAssets(size_t arena_size)
{
    if (g_asset_allocator != nullptr)
        return false; // Already initialized

    if (arena_size > 0)
    {
        g_asset_allocator = CreateArenaAllocator(arena_size);
        if (!g_asset_allocator)
            return false;
    }

    NOZ_LOAD_FONT("fonts/Roboto-Black", Assets.fonts.roboto_black);
    NOZ_LOAD_SHADER("shaders/border_effect", Assets.shaders.border_effect);
    NOZ_LOAD_SHADER("shaders/default", Assets.shaders._default);
    NOZ_LOAD_SHADER("shaders/gamma", Assets.shaders.gamma);
    NOZ_LOAD_SHADER("shaders/gizmo", Assets.shaders.gizmo);
    NOZ_LOAD_SHADER("shaders/lit", Assets.shaders.lit);
    NOZ_LOAD_SHADER("shaders/shadow", Assets.shaders.shadow);
    NOZ_LOAD_SHADER("shaders/text", Assets.shaders.text);
    NOZ_LOAD_SHADER("shaders/ui", Assets.shaders.ui);
    NOZ_LOAD_SHADER("shaders/vignette", Assets.shaders.vignette);
    NOZ_LOAD_TEXTURE("textures/grid", Assets.textures.grid);
    NOZ_LOAD_TEXTURE("textures/icons/meshes/buildings/extractor", Assets.textures.icons.meshes.buildings.extractor);
    NOZ_LOAD_TEXTURE("textures/icons/meshes/buildings/Stone", Assets.textures.icons.meshes.buildings.stone);
    NOZ_LOAD_TEXTURE("textures/palette", Assets.textures.palette);

    // Setup renderer globals from config
    SetShadowPassShader(Assets.shaders.shadow);
    SetGammaPassShader(Assets.shaders.gamma);

    return true;
}

// @uninit
void UnloadAssets()
{
    if (g_asset_allocator != nullptr)
    {
        Destroy(g_asset_allocator);
        g_asset_allocator = nullptr;
        
        // Clear all asset pointers
        memset(&Assets, 0, sizeof(Assets));
    }
}
